---
fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "ciscopuppet": "https://github.com/cisco/cisco-network-puppet-module.git"
  symlinks:
    "cisco_datacentre": "#{source_dir}"
